Implement all features
wuletawwonte/todo-list-react pull request #1
Opened 2022-04-28 10:25 UTC by wuletawwonte

Changes made in this pull request
- Initialize the project using create-react-app 
- Remove all unnecessary files from the project
- Build the homepage of the application using a class-based component 
- Implement raising the state to pass data from a component to sibling components. 
- Add linter configuration from Microverse react-redux repository
- Fix all eslint and stylelint errors 
- Add descriptive README about the project 
- Build todo adding features of the application
- Add editing and deleting a task feature of the app
- Use Gitflow for the workflow
- Style the app based on the styling provided

2022-04-28 21:48 UTC, Achilles-Dev reviewed
The tutorial has a `singlePage.js` file that implements the link to About-app and About-author pages. Please add 
[SinglePage.js](https://ibaslogic.com/routing-with-react-router/#:~:text=Now%2C%20let%E2%80%99s%20see,description%7D%3C/p%3E%0A%20%20%3C/div%3E%0A)

2022-04-28 21:57 UTC, Achilles-Dev reviewed
The About text is displayed on top of the hamburger icon after the About in the sidebar is clicked. See image below

![Screenshot from 2022-04-28 21-51-38](https://user-images.githubusercontent.com/43215910/165854518-c01d2152-5b35-4d9f-ac5a-316195d56be1.png)

2022-04-28 22:01 UTC, Achilles-Dev requested changes
## Hi @wuletawwonte 

Good job so far! 
There are some issues that you still need to work on before merging this branch with the `develop` branch, but you are almost there!

## To highlight :dart: 
- Your repo is professional :heavy_check_mark:
- Well structured files :heavy_check_mark: 
- No linter errors. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-04-29 12:10 UTC, Achilles-Dev commented on src/index.js
>          <Route path="*" element={<NotMatch />} />
Whenever your application loads for the first time, the homepage has `a no match for this page` displayed instead of `HomePage`.
I suggest you move all routes outside the `root. render` and place them inside the `TodoContainer` to prevent this.

2022-04-29 12:14 UTC, Achilles-Dev approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @wuletawwonte, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Some highlights for you
* Correct Gitflow practice ✔️ 
* Professional README ✔️ 
* Clean codebase ✔️ 


![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-04-29 12:16 UTC, wuletawwonte commented
Thank you @Achilles-Dev

2022-04-29 12:17 UTC, merged